spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      port: 6379

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/demo/*.xml
  type-aliases-package: com.rczmm.demo.domain

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

springdoc:
  swagger-ui:
    enabled: true
    path: /index.html




